name: run tests for each PR

run-name: tests
on:
  pull_request:
    branches:
      - "main"
      - "branchName/**"
      - "qa/**"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.6.0
        uses: actions/setup-node@v1
        with:
          node-version: 18.6.0

      - run: npm install
      - run: npm test a

      # - uses: actions/checkout@v3

      # - name: run tests
      #   run: npm test a
